permalink: none
exclude: [ README.md, Gemfile, Gemfile.lock, config.rb, sass/ ]

flickr_id: 96523012@N07

markdown: redcarpet
redcarpet:
    extensions: ["strikethrough"]

base_url: http://clermontech.org

rss:
    title: "Clermont'ech"
    author: "Clermont'ech"
    email: "hello@clermontech.org"

announcement:
    href: http://planet.clermontech.org/
    message: "Retrouvez tous les événements du monde IT Auvergnat sur le <strong>Planet</strong> Clermont'ech !"
