permalink: none
exclude: [ README.md, Gemfile, Gemfile.lock, config.rb, sass/ ]

flickr_id: 96523012@N07

markdown: redcarpet
redcarpet:
    extensions: ["strikethrough"]

announcement:
    href: /api-hours/api-hour-11.html
    message: <i class="fa fa-info-circle"></i> Prochain APIHour le 15 octobre !
