permalink: none
exclude: [ README.md, Gemfile, Gemfile.lock, config.rb, sass/ ]

flickr_id: 96523012@N07

markdown: redcarpet
redcarpet:
    extensions: ["strikethrough"]

base_url: http://clermontech.org

rss:
    title: "Clermont'ech"
    author: "Clermont'ech"
    email: "hello@clermontech.org"

announcement:
    href: http://clermontech.org/blog-posts/phptour-clermont-fd-2016.html
    message: "Nous co-organisons le **PHP Tour 2016** à Clermont-Ferrand !"
