permalink: none
exclude: [ README.md, Gemfile, Gemfile.lock, config.rb, sass/, vendor ]

flickr_id: 96523012@N07

base_url: http://clermontech.org

rss:
    title: "Clermont'ech"
    author: "Clermont'ech"
    email: "hello@clermontech.org"

announcement:
    href: https://www.clermontech.org/workshops/workshop-2-docker.html
    message: "Inscrivez-vous au <strong>workshop Docker</strong> le 4 Juillet à 18h"
