permalink: none
exclude: [ README.md, Gemfile, Gemfile.lock, config.rb, sass/ ]

flickr_id: 96523012@N07

markdown: redcarpet
redcarpet:
    extensions: ["strikethrough"]

announcement:
#    href:
    message: Prochain API Hour le 16 décembre !
